Assignment2/Controllers/GameCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment2.Data;
using Assignment2.Models;

namespace Assignment2.Controllers
{
    public class GameCategoriesController : Controller
    {
        private Assignment2Context db = new Assignment2Context();

        // GET: GameCategories
        public ActionResult Index()
        {
            return View(db.GameCategories.OrderBy(c=>c.Name).ToList());
        }

        // GET: GameCategories/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameCategory gameCategory = db.GameCategories.Find(id);
            if (gameCategory == null)
            {
                return HttpNotFound();
            }
            return View(gameCategory);
        }

        // GET: GameCategories/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GameCategories/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Description")] GameCategory gameCategory)
        {
            if (ModelState.IsValid)
            {
                db.GameCategories.Add(gameCategory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gameCategory);
        }

        // GET: GameCategories/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameCategory gameCategory = db.GameCategories.Find(id);
            if (gameCategory == null)
            {
                return HttpNotFound();
            }
            return View(gameCategory);
        }

        // POST: GameCategories/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Description")] GameCategory gameCategory)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gameCategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gameCategory);
        }

        // GET: GameCategories/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameCategory gameCategory = db.GameCategories.Find(id);
            if (gameCategory == null)
            {
                return HttpNotFound();
            }
            return View(gameCategory);
        }

        // POST: GameCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GameCategory gameCategory = db.GameCategories.Find(id);
            db.GameCategories.Remove(gameCategory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2/Controllers/GamesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Assignment2.Data;
using Assignment2.Models;

namespace Assignment2.Controllers
{
    public class GamesController : Controller
    {
        private Assignment2Context db = new Assignment2Context();

        // GET: Games
        public ActionResult Index(string GameCategory, string search, string sortOrder)
        {
            var games = db.Games.Include(g => g.GameCategory);
            var gamecategories = games.OrderBy(g => g.GameCategory.Name).Select(g => g.GameCategory.Name).Distinct();
            if (!string.IsNullOrEmpty(GameCategory))
            {
                games = games.Where(g => g.GameCategory.Name == GameCategory);
            }

            if (!String.IsNullOrEmpty(search))
            {
                games = games.Where(g => g.Name.Contains(search));
                ViewBag.Search = search;
            }

            switch (sortOrder)
            {
                case "price_desc":
                    games = games.OrderByDescending(g => g.price);
                    break;
                case "price_asc":
                    games = games.OrderBy(g => g.price);
                    break;
                default:
                    games = games.OrderBy(g => g.Id); 
                    break;
            }

            ViewBag.SelectedGameCategory = GameCategory;
            ViewBag.SortOrder = sortOrder;

            
            ViewBag.GameCategory = new SelectList(gamecategories);

            return View(games.ToList());
        }

        // GET: Games/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // GET: Games/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.GameCategories, "Id", "Name");
            return View();
        }

        // POST: Games/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CategoryId,price,ImageUrl,Evaluation,VideoUrl")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Games.Add(game);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.GameCategories, "Id", "Name", game.CategoryId);
            return View(game);
        }

        // GET: Games/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.GameCategories, "Id", "Name", game.CategoryId);
            return View(game);
        }

        // POST: Games/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性；有关
        // 更多详细信息，请参阅 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CategoryId,price,ImageUrl,Evaluation,VideoUrl")] Game game)
        {
            if (ModelState.IsValid)
            {
                db.Entry(game).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.GameCategories, "Id", "Name", game.CategoryId);
            return View(game);
        }

        // GET: Games/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Game game = db.Games.Find(id);
            if (game == null)
            {
                return HttpNotFound();
            }
            return View(game);
        }

        // POST: Games/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Game game = db.Games.Find(id);
            db.Games.Remove(game);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

Assignment2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Game Station</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="~/Content/Site.css" />
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-expand-lg bg-light">
        <div class="container">
            @Html.ActionLink("Game Station", "Index", "Home", new { area = ""  }, new { @class = "navbar-brand" , style = " font-style: italic; " })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="切换导航" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("GameCategory", "Index", "GameCategories", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Game", "Index", "Games", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                @using (Html.BeginForm("Index", "Games", FormMethod.Get, new { @class = "navbar-form navbar-left d-flex align-items-center" }))
                {
                    <div class="form-group">
                        @Html.TextBox("Search", null, new { @class = "form-control", @placeholder = "Srearch Games" })

                    </div>
                    <button type="submit" class="btn btn-default">Search</button>

                }

            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My Game Station</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>